### ISSUE TITLE
Use Travis env var for repo url instead of specifying in .travis.yml

### ISSUE THREAD

**Issue by timwis** [developmentseed/project-seed#49]
Cool project! Just wanted to share something I picked up earlier this week -- Travis CI provides an environment variable `TRAVIS_REPO_SLUG`, which would resolve to `developmentseed/project-seed` (or whatever repo slug Travis is connected to). You can use this to construct the remote URL so that forkers of this project don't need to remember to change `GH_REF` in `.travis.yml`.

Here's an [example](https://github.com/timwis/static-api/blob/master/deploy.sh) of how I used this earlier this week. Coincidentally, I think we may have read some of the same articles when writing `deploy.sh`!

**Comment by jflasher** [comment]
Thanks @timwis ! This is a good addition, I'll get it added in. Unfortunately, forkers will still need to update the GH_TOKEN, but at least this is one less step!

Also, why do you put all the commands in your bash script as one logical line with the `&&`'s?

**Comment by timwis** [comment]
Actually, one thing I've started doing is using Travis CI's website for environment variables, as it removes the need for forkers to use the travis command line tool and modify the `.travis.yml` file at all. If you go to the settings page (travis-ci.org/your-username/static-api/settings) you can add `GH_TOKEN` as an env var right there.

As to the `&&`s on each line, I can't say I remember... I'm pretty sure it was to ensure that if any of the commands failed that it wouldn't try to keep executing the rest. But perhaps `set -e` takes care of that...

**Comment by jflasher** [comment]
Oh yeah, I think that's what `set -e` does, but am not 100% positive. As for the Travis env vars on the website, I generally prefer not to go that route since I like to keep everything with the code if possible. Generally, the only time I handle them via the website is if I am forking the project and need the env vars to be repo specific. Which I guess when I say it is kind of exactly what we're doing here! I just don't know if I can get over my dislike of having things needed to be defined via Travis only.

**Comment by jflasher** [comment]
Closed with https://github.com/developmentseed/project-seed/pull/50
