### ISSUE TITLE
Include Compass

### ISSUE THREAD

**Issue by drewbo** [developmentseed/project-seed#6]
Or something which replicates it's functionality (or at least the parts we want) without using ruby

cc: @danielfdsilva @ricardomestre

**Comment by jflasher** [comment]
Unless Compass is the only way to get it, then we can roll with that too.

**Comment by ricardomestre** [comment]
If weight and performance are the issue, maybe we can go with [Bourbon](http://bourbon.io/) instead of Compass, since it provides most of the same capabilities and it is very lightweight in comparison.

To be honest, though, I've only used Bourbon once. I didn't like it much because it lacked a lot of the functionalities covered by Compass. Looking at the documentation now and after reading some [comparison articles](http://www.sitepoint.com/compass-or-bourbon-sass-frameworks/), Bourbon seems a pretty solid solution these days. I would say that the only caveat is that we will need to come up with our own Compass inspired image-related helpers, if we need those for a specific project.

**Comment by kamicut** [comment]
I don't have anything to contribute 

![](http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2014/05/1401058926doge-framework.jpg)

**Comment by jflasher** [comment]
Personally, I'm not trying to get us to move to something else if we don't want to. If Compass is the best tool for what we want to do, then we should definitely use it. Just wanted to see if we could drop a dependency if possible.

**Comment by anandthakker** [comment]
I don't have much of an opinion about Compass (or Bourbon) itself, but I do think that, if it were at all feasible, it would be great to distill the mixins and functions we want and just check those in as a `_base.scss` file.

My reasons:
1. I think it can be really helpful to have the underlying code for this stuff at your fingertips, both to understand it and to use it as a model for how to write good, reusable (s)css.  (Technically the code for Bourbon and Compass are available, but realistically, since they're buried as dependencies and probably include quite a bit more than we're really using, I'd be less likely to use open up and browse that source...)
2. We probably want to have something like a `_base.scss` anyway, for common, reusable stuff that's relevant to our kind of work but not present in Bourbon or Compass.  (Map-related stuff comes to mind.)  Also, we can tweak/improve what's already there.
3. With autoprefixer in place, we've taken care of the part of these frameworks that changes the fastest, which means there's much less of a downside to just copying their best stuff and including it statically.

**Comment by danielfdsilva** [comment]
We've been using bourbon and has been working. closing
